# Generated by Django 5.0.6 on 2024-06-14 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='rank_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute', models.CharField(max_length=100)),
                ('program', models.CharField(max_length=100)),
                ('seat_type', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('opening_rank', models.IntegerField()),
                ('closing_rank', models.IntegerField()),
                ('year', models.IntegerField()),
                ('roundNo', models.IntegerField()),
            ],
        ),
    ]
